"use client"

import * as React from "react"
import {
  ArrowUpRightIcon,
  CheckIcon,
  CopyIcon,
  GithubLogoIcon,
  LinkedinLogoIcon,
  XLogoIcon,
} from "@phosphor-icons/react/ssr"
import { toast } from "sonner"

import { cn } from "@/lib/utils"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { ShaderBackground } from "@/components/ui/shader-background"
import { Switch } from "@/components/ui/switch"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"

/*
 * "A portfolio with props." Deepak builds a component library, so the
 * portfolio reads like one, and visitors can re-skin it with that library.
 * Artwork lives in /public/work (generated by scripts/build-portfolio-art.mjs).
 */

const EMAIL = "deepak@1619.in"
const container = "mx-auto w-full max-w-6xl px-5 sm:px-8"

/* ------------------------------------------------------------------ utils */

function useInView<T extends HTMLElement>(margin = "0px 0px -10% 0px") {
  const ref = React.useRef<T>(null)
  const [inView, setInView] = React.useState(false)
  React.useEffect(() => {
    const el = ref.current
    if (!el) return
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      setInView(true) // eslint-disable-line react-hooks/set-state-in-effect
      return
    }
    const io = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setInView(true)
          io.disconnect()
        }
      },
      { rootMargin: margin }
    )
    io.observe(el)
    return () => io.disconnect()
  }, [margin])
  return [ref, inView] as const
}

function Reveal({ className, delay = 0, ...props }: React.ComponentProps<"div"> & { delay?: number }) {
  const [ref, shown] = useInView<HTMLDivElement>()
  return (
    <div
      ref={ref}
      data-shown={shown || undefined}
      style={{ transitionDelay: `${delay}ms` }}
      className={cn(
        "translate-y-8 opacity-0 transition-[opacity,translate] duration-700 ease-(--du-ease-out) data-shown:translate-y-0 data-shown:opacity-100",
        className
      )}
      {...props}
    />
  )
}

/** Visitors can re-skin the page with Deepak's own library. */
function useDocumentStyle() {
  const [style, setStyle] = React.useState("raw")
  React.useEffect(() => {
    const read = () => setStyle(document.documentElement.getAttribute("data-style") ?? "raw")
    read()
    const mo = new MutationObserver(read)
    mo.observe(document.documentElement, { attributes: true, attributeFilter: ["data-style"] })
    return () => mo.disconnect()
  }, [])
  const set = (next: string) => {
    document.documentElement.setAttribute("data-style", next)
    try {
      localStorage.setItem("dumb-style", next)
    } catch {}
  }
  return [style, set] as const
}

/* ------------------------------------------------------------- floating nav */

function FloatingNav({ condensed }: { condensed: boolean }) {
  return (
    <div className="pointer-events-none fixed inset-x-0 top-4 z-50 flex justify-center px-4">
      <nav
        aria-label="Main"
        data-condensed={condensed || undefined}
        className="pointer-events-auto flex items-center gap-1 rounded-(--du-radius-control) border-(length:--du-border-overlay) border-border bg-popover/85 p-1.5 shadow-(--du-shadow-overlay) backdrop-blur-xl transition-[gap,padding] duration-500 ease-(--du-ease-out) data-condensed:gap-0.5"
      >
        <a
          href="#top"
          aria-label="Deepak Kumar, top of page"
          className="du-display inline-flex size-9 items-center justify-center rounded-(--du-radius-control) bg-primary text-sm text-primary-foreground"
        >
          DK
        </a>
        {["Work", "About", "Writing"].map((item) => (
          <a
            key={item}
            href={`#${item.toLowerCase()}`}
            className="hidden h-9 items-center rounded-(--du-radius-control) px-3.5 text-sm text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground sm:inline-flex"
          >
            {item}
          </a>
        ))}
        <Button size="sm" asChild className="ml-1">
          <a href="#contact">Say hello</a>
        </Button>
      </nav>
    </div>
  )
}

/* ------------------------------------------------------------------- hero */

const props = [
  { name: "role", value: '"design engineer"', className: "-left-6 top-10 sm:-left-16" },
  { name: "stack", value: '{["React", "TS", "GLSL"]}', className: "-right-4 top-1/3 sm:-right-24" },
  { name: "based", value: '"India"', className: "-left-4 bottom-24 sm:-left-20" },
  { name: "available", value: "", className: "-right-2 bottom-8 sm:-right-10" },
]

function Hero({ sentinelRef }: { sentinelRef: React.Ref<HTMLDivElement> }) {
  return (
    <section id="top" className="relative isolate overflow-hidden pt-28 sm:pt-32">
      <ShaderBackground intensity={0.45} className="-z-10 [mask-image:linear-gradient(to_bottom,black,transparent_85%)]" />
      <div className={cn(container, "grid items-center gap-14 pb-20 lg:min-h-[calc(100dvh-8rem)] lg:grid-cols-[minmax(0,1.25fr)_minmax(0,0.75fr)]")}>
        <div className="grid gap-8">
          <Reveal>
            <span className="inline-flex items-center gap-2 font-mono text-sm text-muted-foreground">
              <span className="relative flex size-2">
                <span className="absolute inline-flex size-full animate-ping rounded-full bg-success opacity-60 motion-reduce:hidden" />
                <span className="relative inline-flex size-2 rounded-full bg-success" />
              </span>
              Taking on two projects from November
            </span>
          </Reveal>
          <Reveal delay={80}>
            <h1 className="du-display text-[3.4rem] leading-[0.92] sm:text-[5.5rem] lg:text-[7.25rem]">
              Deepak
              <br />
              Kumar
            </h1>
          </Reveal>
          <Reveal delay={160} className="grid gap-6">
            <p className="max-w-[40ch] text-lg leading-relaxed text-muted-foreground sm:text-xl">
              Design engineer at 1619.in. I design interfaces and then build them, so nothing gets lost in between.
            </p>
            <div className="flex flex-wrap gap-3">
              <Button size="lg" asChild>
                <a href="#work">See the work</a>
              </Button>
              <Button size="lg" variant="outline" asChild className="bg-background">
                <a href="#contact">Start a project</a>
              </Button>
            </div>
          </Reveal>
        </div>

        <Reveal delay={220} className="relative mx-auto w-full max-w-sm">
          <figure className="relative m-0 overflow-hidden rounded-(--du-radius-surface) border-(length:--du-border-surface) border-border shadow-(--du-shadow-overlay)">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/work/portrait.svg" alt="Illustrated portrait of Deepak Kumar" className="block aspect-[4/5] w-full object-cover" />
          </figure>
          {props.map((prop, index) => (
            <span
              key={prop.name}
              style={{ animationDelay: `${index * -1.3}s` }}
              className={cn(
                "absolute hidden animate-[pf-float_6s_ease-in-out_infinite] rounded-(--du-radius-item) border-(length:--du-border-overlay) border-border bg-popover px-3 py-1.5 font-mono text-xs whitespace-nowrap text-popover-foreground shadow-(--du-shadow-overlay) motion-reduce:animate-none sm:block",
                prop.className
              )}
            >
              <span className="text-muted-foreground">{prop.name}</span>
              {prop.value ? (
                <>
                  <span className="text-muted-foreground">=</span>
                  <span>{prop.value}</span>
                </>
              ) : null}
            </span>
          ))}
        </Reveal>
      </div>
      <div ref={sentinelRef} className="h-px" aria-hidden="true" />
    </section>
  )
}

/* ---------------------------------------------------------------- ticker */

const skills = ["Design systems", "React", "TypeScript", "Accessibility", "WebGL", "Motion", "Tokens", "Next.js", "Radix", "Tailwind"]

function Ticker() {
  return (
    <div className="overflow-hidden border-y-(length:--du-rule) border-border bg-sunken py-5" aria-label="Skills">
      <div className="flex w-max animate-[pf-marquee_40s_linear_infinite] gap-10 motion-reduce:animate-none">
        {[...skills, ...skills].map((skill, i) => (
          <span key={i} aria-hidden={i >= skills.length || undefined} className="du-display flex items-center gap-10 text-2xl whitespace-nowrap text-muted-foreground">
            {skill}
            <span className="size-2 rotate-45 bg-(--highlight)" />
          </span>
        ))}
      </div>
    </div>
  )
}

/* ------------------------------------------------------------------- work */

const projects = [
  { title: "Dumb UI", kind: "Design system", year: "2026", image: "dumb-ui", summary: "One component API, three visual languages. Tokens, a shadcn registry and a docs playground." },
  { title: "1619 Deploy", kind: "Product", year: "2025", image: "deploy", summary: "Preview environments for every branch, with comments pinned to the real page." },
  { title: "Atlas Status", kind: "Dashboard", year: "2025", image: "atlas", summary: "Uptime and error budgets for forty services, readable at a glance during an incident." },
  { title: "Fernhill Studio", kind: "Brand site", year: "2024", image: "fernhill", summary: "A print studio's website that feels like the paper they sell." },
  { title: "Terrain", kind: "Data visualisation", year: "2024", image: "terrain", summary: "Elevation maps for trail planning, drawn on the GPU at sixty frames a second." },
]

function Work() {
  return (
    <section id="work" className={cn(container, "grid gap-12 py-24 sm:py-32 lg:grid-cols-[minmax(0,0.6fr)_minmax(0,1.4fr)] lg:gap-16")}>
      <div className="lg:sticky lg:top-28 lg:self-start">
        <Reveal className="grid gap-4">
          <h2 className="du-display text-5xl leading-none sm:text-6xl">Selected work</h2>
          <p className="max-w-[30ch] text-muted-foreground">Five projects from the last three years. Each one shipped.</p>
          <span className="font-mono text-sm text-muted-foreground">{projects.length} items</span>
        </Reveal>
      </div>
      <div className="grid gap-16">
        {projects.map((project, index) => (
          <Reveal key={project.title}>
            <a href="#" className="group grid gap-5">
              <div className="relative overflow-hidden rounded-(--du-radius-surface) border-(length:--du-border-surface) border-border shadow-(--du-shadow-surface)">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`/work/${project.image}.svg`}
                  alt={`${project.title} cover`}
                  loading="lazy"
                  className="block aspect-[3/2] w-full object-cover transition-transform duration-700 ease-(--du-ease-out) group-hover:scale-[1.04]"
                />
                <span className="absolute top-4 left-4 rounded-(--du-radius-item) bg-background/85 px-2.5 py-1 font-mono text-xs backdrop-blur-sm">
                  {String(index + 1).padStart(2, "0")}
                </span>
                <span className="absolute right-4 bottom-4 inline-flex size-12 translate-y-3 items-center justify-center rounded-(--du-radius-control) bg-primary text-primary-foreground opacity-0 shadow-(--du-shadow-primary) transition-all duration-500 ease-(--du-ease-out) group-hover:translate-y-0 group-hover:opacity-100">
                  <ArrowUpRightIcon weight="bold" className="size-5" />
                </span>
              </div>
              <div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-baseline sm:gap-6">
                <h3 className="du-display text-3xl">{project.title}</h3>
                <span className="flex items-center gap-2">
                  <Badge variant="secondary">{project.kind}</Badge>
                  <span className="font-mono text-xs text-muted-foreground">{project.year}</span>
                </span>
                <p className="max-w-[52ch] text-muted-foreground sm:col-span-2">{project.summary}</p>
              </div>
            </a>
          </Reveal>
        ))}
      </div>
    </section>
  )
}

/* --------------------------------------------------------------- re-skin */

function Reskin() {
  const [style, setStyle] = useDocumentStyle()
  return (
    <section className="relative isolate overflow-hidden border-y-(length:--du-rule) border-border">
      <ShaderBackground className="-z-10" intensity={0.8} />
      <div className="pointer-events-none absolute inset-0 -z-10 bg-background/60" />
      <div className={cn(container, "grid items-center gap-10 py-24 sm:py-28 lg:grid-cols-2")}>
        <Reveal className="grid gap-4">
          <h2 className="du-display text-4xl leading-tight sm:text-5xl">This site runs on my own library.</h2>
          <p className="max-w-[42ch] text-lg text-muted-foreground">
            Pick a material. Every button, field and surface on this page changes with it.
          </p>
        </Reveal>
        <Reveal delay={120} className="grid gap-6 justify-self-start rounded-(--du-radius-surface) border-(length:--du-border-surface) border-border bg-card p-6 shadow-(--du-shadow-surface) lg:justify-self-end">
          <ToggleGroup
            type="single"
            variant="outline"
            value={style}
            onValueChange={(value) => value && setStyle(value)}
            aria-label="Page style"
          >
            <ToggleGroupItem value="raw">Raw</ToggleGroupItem>
            <ToggleGroupItem value="silk">Silk</ToggleGroupItem>
            <ToggleGroupItem value="volume">Volume</ToggleGroupItem>
          </ToggleGroup>
          <div className="flex items-center justify-between gap-6">
            <Label htmlFor="pf-demo-switch">Notify me about new work</Label>
            <Switch id="pf-demo-switch" defaultChecked />
          </div>
          <Button className="w-full" asChild>
            <a href="https://ui.1619.in">Get Dumb UI</a>
          </Button>
        </Reveal>
      </div>
    </section>
  )
}

/* ------------------------------------------------------------------ about */

const capabilities = {
  systems: ["Token architectures that survive rebrands", "Component APIs five teams can share", "Docs, registries and a release process"],
  engineering: ["React, Next.js and TypeScript in production", "Accessible primitives on Radix", "WebGL and shaders for the moments that matter"],
  product: ["From a rough flow to a shipped screen", "Prototypes on real data, not lorem ipsum", "Design review on the branch, not a screenshot"],
}

const roles = [
  { years: "2024 to now", role: "Design engineer", place: "1619.in" },
  { years: "2021 to 2024", role: "Front-end lead", place: "Fernhill Studio" },
  { years: "2019 to 2021", role: "UI engineer", place: "Atlas Maps" },
]

function About() {
  return (
    <section id="about" className={cn(container, "grid gap-16 py-24 sm:py-32 lg:grid-cols-2")}>
      <Reveal className="grid content-start gap-8">
        <h2 className="du-display text-4xl leading-tight sm:text-5xl">Design and code. One person, no handoff.</h2>
        <Tabs defaultValue="systems">
          <TabsList>
            <TabsTrigger value="systems">Systems</TabsTrigger>
            <TabsTrigger value="engineering">Engineering</TabsTrigger>
            <TabsTrigger value="product">Product</TabsTrigger>
          </TabsList>
          {Object.entries(capabilities).map(([key, items]) => (
            <TabsContent key={key} value={key} className="pt-3">
              <ul className="grid gap-3.5">
                {items.map((item) => (
                  <li key={item} className="flex items-start gap-3 text-[1.0625rem]">
                    <CheckIcon weight="bold" className="mt-1 size-4 shrink-0 text-primary" />
                    {item}
                  </li>
                ))}
              </ul>
            </TabsContent>
          ))}
        </Tabs>
      </Reveal>
      <Reveal delay={120} className="grid content-start">
        <span className="du-label mb-6 text-muted-foreground">Experience</span>
        {roles.map((role, index) => (
          <div key={role.place}>
            {index > 0 && <Separator className="my-6" />}
            <div className="grid gap-1 sm:grid-cols-[9rem_minmax(0,1fr)] sm:gap-6">
              <span className="font-mono text-sm text-muted-foreground">{role.years}</span>
              <span className="grid">
                <span className="du-display text-2xl">{role.role}</span>
                <span className="text-muted-foreground">{role.place}</span>
              </span>
            </div>
          </div>
        ))}
      </Reveal>
    </section>
  )
}

/* ---------------------------------------------------------------- writing */

const posts = [
  { title: "Dumb components, smart styles", date: "Oct 2026", read: "6 min" },
  { title: "Tokens are an API. Version them like one.", date: "Aug 2026", read: "8 min" },
  { title: "What a shader taught me about frame budgets", date: "May 2026", read: "5 min" },
]

function Writing() {
  return (
    <section id="writing" className={cn(container, "pb-24 sm:pb-32")}>
      <Reveal className="mb-6">
        <h2 className="du-display text-4xl sm:text-5xl">Writing</h2>
      </Reveal>
      <ul>
        {posts.map((post, index) => (
          <Reveal key={post.title} delay={index * 80}>
            <li>
              <a href="#" className="group flex flex-wrap items-baseline gap-x-6 gap-y-1 border-b-(length:--du-rule) border-border py-7">
                <span className="du-display flex-1 text-2xl transition-transform duration-500 ease-(--du-ease-out) group-hover:translate-x-2 sm:text-[2rem]">
                  {post.title}
                </span>
                <span className="font-mono text-xs text-muted-foreground">
                  {post.date} · {post.read}
                </span>
                <ArrowUpRightIcon className="size-5 text-muted-foreground transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" />
              </a>
            </li>
          </Reveal>
        ))}
      </ul>
    </section>
  )
}

/* ---------------------------------------------------------------- contact */

function Contact() {
  const [copied, setCopied] = React.useState(false)
  const [sending, setSending] = React.useState(false)

  return (
    <section id="contact" className="border-t-(length:--du-rule) border-border bg-sunken">
      <div className={cn(container, "grid gap-14 py-24 sm:py-32 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]")}>
        <Reveal className="grid content-start gap-8">
          <h2 className="du-display text-5xl leading-[0.95] sm:text-7xl">Have something to build?</h2>
          <button
            type="button"
            onClick={async () => {
              try {
                await navigator.clipboard.writeText(EMAIL)
                setCopied(true)
                window.setTimeout(() => setCopied(false), 1600)
              } catch {}
            }}
            className="group inline-flex w-fit cursor-pointer items-center gap-3 text-2xl underline decoration-(--highlight) decoration-2 underline-offset-[0.3em] sm:text-3xl"
          >
            {EMAIL}
            {copied ? <CheckIcon className="size-6" /> : <CopyIcon className="size-6 opacity-50 group-hover:opacity-100" />}
            <span className="sr-only" aria-live="polite">{copied ? "Copied" : ""}</span>
          </button>
          <div className="flex gap-2">
            {[
              { label: "GitHub", icon: GithubLogoIcon, href: "https://github.com/KumarDeepak16" },
              { label: "LinkedIn", icon: LinkedinLogoIcon, href: "#" },
              { label: "X", icon: XLogoIcon, href: "#" },
            ].map((link) => (
              <Button key={link.label} variant="outline" size="icon" asChild>
                <a href={link.href} aria-label={link.label}>
                  <link.icon />
                </a>
              </Button>
            ))}
          </div>
        </Reveal>
        <Reveal delay={120}>
          <form
            className="grid gap-4 rounded-(--du-radius-surface) border-(length:--du-border-surface) border-border bg-card p-6 shadow-(--du-shadow-surface) sm:p-8"
            onSubmit={(event) => {
              event.preventDefault()
              const form = event.currentTarget
              setSending(true)
              window.setTimeout(() => {
                setSending(false)
                toast.success("Message sent", { description: "I reply within two working days." })
                form.reset()
              }, 1200)
            }}
          >
            <div className="grid gap-2">
              <Label htmlFor="pf-name">Name</Label>
              <Input id="pf-name" required autoComplete="name" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="pf-email">Email</Label>
              <Input id="pf-email" type="email" required autoComplete="email" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="pf-message">Project</Label>
              <Textarea id="pf-message" required showCount maxLength={600} placeholder="What are you building, and by when?" />
            </div>
            <Button type="submit" loading={sending} className="w-full">
              Send message
            </Button>
          </form>
        </Reveal>
      </div>
      <div className={cn(container, "flex flex-wrap items-center justify-between gap-3 pb-24 text-xs text-muted-foreground")}>
        <span>© 2026 Deepak Kumar</span>
        <a href="https://ui.1619.in" className="hover:text-foreground">Built with Dumb UI</a>
      </div>
    </section>
  )
}

/* ------------------------------------------------------------------- page */

export default function PortfolioTemplate() {
  const [sentinel, pastHero] = useInView<HTMLDivElement>("0px")
  return (
    <div className="min-h-dvh overflow-x-hidden bg-background text-foreground">
      <style>{`
        @keyframes pf-float { 0%, 100% { translate: 0 0 } 50% { translate: 0 -8px } }
        @keyframes pf-marquee { to { transform: translateX(-50%) } }
      `}</style>
      <FloatingNav condensed={pastHero} />
      <main>
        <Hero sentinelRef={sentinel} />
        <Ticker />
        <Work />
        <Reskin />
        <About />
        <Writing />
        <Contact />
      </main>
    </div>
  )
}
